### ISSUE TITLE
pp1.7.3 /components/server-map2/jquery.ServerMap2.js not found htIcons

### ISSUE THREAD

**Issue by caius-kong** [bbossgroups/pinpoint-plugin-generate#3]
pinpoint 1.7.3
/components/server-map2/jquery.ServerMap2.js not found htIcons

**Comment by yin-bp** [comment]
pinpoint 1.7.3
/components/server-map2/jquery.ServerMap2.js not found htIcons
Ignore this. Pinpoint 1.7.3 need not to config plugin icons in /components/server-map2/jquery.ServerMap2.js

**Comment by caius-kong** [comment]
OK, but this causes a problem. I want to intercept our self-developed middleware. Although the plug-in package generated by your project intercepts my target class, it does not show this middleware in the application's main view (similar to app with an arrow pointing to redis).

**Comment by yin-bp** [comment]
What is your plugin generate config ,and you should put the images icons to ‘webapp\images\servermap’ and ‘webapp\images\icons’

Please set the plugin.interceptor.type like this:
plugin.interceptor.type=spantrace

This tool has been tested on 1.6.2. I'll test it on 1.7.3 soon.

**Comment by yin-bp** [comment]
Pinpoint 1.7.3 has a bug which caused the generated plugin can't working.I have reported this bug to pinpoint develop team and It has been fixed by them:
https://github.com/naver/pinpoint/issues/4283
