### ISSUE TITLE
把依赖的包打入jar包

### ISSUE THREAD

**Issue by JangNum** [bbossgroups/pinpoint-plugin-generate#9]
非常感谢你们能够把这个工具开源出来。我在工具生成的代码基础上做了修改，使用gradle引入了相关第三方jar包，但是请问怎么能把第三方jar包正确的打到插件包里呢？ 第三方jar包在插件包里有位置要求吗？

**Comment by yin-bp** [comment]
第三方包不需要引入插件里面，放到自己的应用里面即可，只需要在bboss里面做compileOnly模式导入第三方包即可

**Comment by JangNum** [comment]
> 第三方包不需要引入插件里面，放到自己的应用里面即可，只需要在bboss里面做compileOnly模式导入第三方包即可

非常感谢
